path_to_images: "/home/mluser/Schreibtisch/data/dataset_test_real/"  # / at end!

store_belief_maps: True
show_belief_maps: False
store_images: False

# Cuboid dimension in cm x,y,z
dimensions: {
    "carrier_empty": [19.8,9.0,17.7]
}

draw_colors: {
    # [13, 255, 128],  # green
    # [255, 255, 255], # while
    # [0, 104, 255],   # blue
    # [217,12, 232],   # magenta
    # [255, 101, 0],   # orange
    # [232, 222, 12],  # yellow
    "carrier_empty": [0, 104, 255],
}

# Camera intrinsics
camera_settings: {
    "name": "Realsense",
    "width": 400,
    "height": 400,
    "fx": 513.95,
    "fy": 514.1,
    "cx": 203.57,
    "cy": 198.37
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
