#camera_color_width: 1280
#camera_color_height: 720
#camera_depth_width: 1280
#camera_depth_height: 720
#camera_color_fps: 30
#camera_depth_fps: 30

#aruco_marker_length: 0.0576

camera_width: 1280
camera_height: 720
outputImage_size: 400
object_name: 'carrier_empty'

path_to_obj_stl: '/home/mluser/catkin_ws/src/mt/cad/product.stl'
# path_to_obj_stl: '/home/johannes/catkin_ws/src/mt/cad/product.stl'
path_to_store: '/home/mluser/catkin_ws/src/data/single/carrier_empty/'
#path_to_store: '/home/johannes/catkin_ws/src/data/'

print_debug: false
pause: false

PoseRandomization:
  phiInc: -10
  thetaInc: 15
  numHorizontal: 15
  thetaMax: 65
  rRmin: -0.1
  rRmax: 0.1
  numRandomGoals: 3
  rotate4Min: 2
  rotate4Max: 6
  rotate5Min: 2
  rotate5Max: 6
  rotate6Min: 5
  rotate6Max: 65
