#camera_color_width: 1280
#camera_color_height: 720
#camera_depth_width: 1280
#camera_depth_height: 720
#camera_color_fps: 30
#camera_depth_fps: 30

#aruco_marker_length: 0.0576

camera_width: 1280
camera_height: 720
outputImage_size: 400
object_name: 'holder_empty'

path_to_obj_stl: '/home/mluser/catkin_ws/src/mt/cad/holder.stl' #product.stl'
# path_to_obj_stl: '/home/johannes/catkin_ws/src/mt/cad/product.stl'
path_to_store: '/home/mluser/catkin_ws/src/data/holder/'
#path_to_store: '/home/johannes/catkin_ws/src/data/'

print_debug: false
pause: false

PoseRandomization:
  phiInc: -10
  thetaInc: 15
  numHorizontal: 15
  thetaMax: 65
  rRmin: -0.1
  rRmax: 0.1
  numRandomGoals: 3
  rotate4Min: 2
  rotate4Max: 6
  rotate5Min: 2
  rotate5Max: 6
  rotate6Min: 5
  rotate6Max: 65

carrier_empty:
  transformTo:
    object_img_center: [0, 0, 0.05, 0, 0, 0] # from marker - x, y, z, rx, ry, rz [deg] for rxyz
    object: [0, 0, -0.0075, 0, 0, 0]
    object_origin: [0, 0, -0.0075, -90, 0, -180]
    c_0: [-0.1185, -0.099, 0,    0, 0, 0]
    c_1: [-0.1185,  0.099, 0,    0, 0, 0]
    c_2: [-0.1185,  0.099, 0.09, 0, 0, 0]
    c_3: [-0.1185, -0.099, 0.09, 0, 0, 0]
    c_4: [ 0.0585, -0.099, 0,    0, 0, 0]
    c_5: [ 0.0585,  0.099, 0,    0, 0, 0]
    c_6: [ 0.0585,  0.099, 0.09, 0, 0, 0]
    c_7: [ 0.0585, -0.099, 0.09, 0, 0, 0]
    c_8: [-0.03, 0, 0.045, 0, 0, 0]

holder_empty:
  transformTo:
    object_img_center: [0.05806, -0.0305, 0, 0, 0, 0] # from marker - x, y, z, rx, ry, rz [deg] for rxyz
    object: [-0.01915, -0.0305, -0.038, 0, 0, 0]
    object_origin: [-0.01915, -0.0305, -0.038, -90, 0, -180]
    c_0: [-0.01685, -0.099, 0,    0, 0, 0]
    c_1: [-0.01685,  0.099, 0,    0, 0, 0]
    c_2: [-0.01685,  0.099, 0.06, 0, 0, 0]
    c_3: [-0.01685, -0.099, 0.06, 0, 0, 0]
    c_4: [ 0.14327, -0.099, 0,    0, 0, 0]
    c_5: [ 0.14327,  0.099, 0,    0, 0, 0]
    c_6: [ 0.14327,  0.099, 0.06, 0, 0, 0]
    c_7: [ 0.14327, -0.099, 0.06, 0, 0, 0]
    c_8: [ 0.06321,  0,     0.03, 0, 0, 0]
